async function main() {
  console.log("done");
}

main().catch((error) => {
  console.error(error);
});
